### ISSUE TITLE
New export as string option

### ISSUE THREAD

**Issue by neubee** [spirit-island-builder/spirit-island-builder#133]
@resonant-gamedesign What do you think of adding another export/sharing option that's easier to share than a full html file?

The idea is that we can take the the object that holds the values for a tab (i.e. the spiritBoard object) and turn it into a string using base64. The string could then be imported to the site either via a text input, or as part of the URL.

Since there's so much data the string gets fairly long, but it's still usable. The spiritBoard looks like this

`eyJkZW1vQm9hcmRXYXNMb2FkZWQiOnRydWUsInByZXZpZXdCb2FyZCI6eyJpc1Zpc2libGUiOmZhbHNlfSwibmFtZUFuZEFydCI6eyJpc1Zpc2libGUiOmZhbHNlLCJuYW1lIjoiVm9sY2FubyBMb29taW5nIEhpZ2giLCJhcnRQYXRoIjoiZXhhbXBsZTEucG5nIiwiYXJ0U2NhbGUiOiIxOTAlIiwiYmFubmVyUGF0aCI6ImV4YW1wbGUyLnBuZyIsImVuZXJneUJhbm5lclBhdGgiOiJleGFtcGxlMi5wbmciLCJlbmVyZ3lCYW5uZXJTY2FsZSI6IjUwJSIsInBsYXlzQmFubmVyUGF0aCI6ImV4YW1wbGUyLnBuZyIsInBsYXlzQmFubmVyU2NhbGUiOiI1MCUiLCJhcnRpc3RDcmVkaXQiOiIifSwic3BlY2lhbFJ1bGVzIjp7ImlzVmlzaWJsZSI6ZmFsc2UsInJ1bGVzIjpbeyJpZCI6MCwibmFtZSI6Ik1vdW50YWluIEhvbWUiLCJlZmZlY3QiOiJZb3VyIHtwcmVzZW5jZX0gbWF5IG9ubHkgYmUgYWRkZWQvbW92ZWQgaW50byBNb3VudGFpbnMuIn0seyJpZCI6MSwibmFtZSI6IkNPTExBUFNFIElOIEEgQkxBU1QgT0YgTEFWQSBBTkQgU1RFQU0iLCJlZmZlY3QiOiJXaGVuIHlvdXIge3ByZXNlbmNlfSBpcyBkZXN0cm95ZWQsIGluIHRoYXQgbGFuZCwgZGVhbCAxIERhbWFnZSBwZXIgZGVzdHJveWVkIHtwcmVzZW5jZX0gdG8gYm90aCBJbnZhZGVycyBhbmQgdG8ge2RhaGFufS4ifSx7ImlkIjoyLCJuYW1lIjoiVk9MQ0FOSUMgUEVBS1MgVE9XRVIgT1ZFUiBUSEUgTEFORFNDQVBFIiwiZWZmZWN0IjoiWW91ciBQb3dlciBDYXJkcyBnYWluIHtnYWluLXJhbmdlLTF9IGlmIHlvdSBoYXZlIDMgb3IgbW9yZSB7cHJlc2VuY2V9IGluIHRoZSBvcmlnaW4gbGFuZC4ifV19LCJncm93dGgiOnsiaXNWaXNpYmxlIjpmYWxzZSwidXNlR3Jvd3RoU2V0cyI6ZmFsc2UsImRpcmVjdGlvbnMiOiJQaWNrIE9uZSIsImdyb3d0aFNldHMiOlt7ImlkIjowLCJjaG9pY2VUZXh0IjoiR3Jvd3RoIChQaWNrIE9uZSkiLCJncm93dGhHcm91cHMiOlt7ImlkIjowLCJjb3N0IjpudWxsLCJ0aW50IjpudWxsLCJ0aXRsZSI6bnVsbCwiaGFzQ29zdCI6ZmFsc2UsImhhc1RpbnQiOmZhbHNlLCJoYXNUaXRsZSI6ZmFsc2UsImdyb3d0aEFjdGlvbnMiOlt7ImlkIjowLCJlZmZlY3QiOiJyZWNsYWltLWFsbCJ9LHsiaWQiOjEsImVmZmVjdCI6ImdhaW4tcG93ZXItY2FyZCJ9LHsiaWQiOjIsImVmZmVjdCI6ImdhaW4tZW5lcmd5KDMpIn1dfSx7ImlkIjoxLCJjb3N0IjpudWxsLCJ0aW50IjpudWxsLCJ0aXRsZSI6bnVsbCwiaGFzQ29zdCI6ZmFsc2UsImhhc1RpbnQiOmZhbHNlLCJoYXNUaXRsZSI6ZmFsc2UsImdyb3d0aEFjdGlvbnMiOlt7ImlkIjowLCJlZmZlY3QiOiJhZGQtcHJlc2VuY2UoMCkifSx7ImlkIjoxLCJlZmZlY3QiOiJhZGQtcHJlc2VuY2UoMCkifV19LHsiaWQiOjIsImNvc3QiOm51bGwsInRpbnQiOm51bGwsInRpdGxlIjpudWxsLCJoYXNDb3N0IjpmYWxzZSwiaGFzVGludCI6ZmFsc2UsImhhc1RpdGxlIjpmYWxzZSwiZ3Jvd3RoQWN0aW9ucyI6W3siaWQiOjAsImVmZmVjdCI6ImdhaW4tcG93ZXItY2FyZCJ9LHsiaWQiOjEsImVmZmVjdCI6ImFkZC1wcmVzZW5jZSg0KSJ9LHsiaWQiOjIsImVmZmVjdCI6ImdhaW4tY2FyZC1wbGF5KDEpIn0seyJpZCI6MywiZWZmZWN0IjoiZ2Fpbi1lbmVyZ3koMikifV19XX1dfSwicHJlc2VuY2VUcmFjayI6eyJpc1Zpc2libGUiOmZhbHNlLCJ1c2VNaWRkbGVOb2RlcyI6ZmFsc2UsIm5vdGUiOiIiLCJlbmVyZ3lOb2RlcyI6W3siaWQiOjAsImVmZmVjdCI6IjEifSx7ImlkIjoxLCJlZmZlY3QiOiIyIn0seyJpZCI6MiwiZWZmZWN0IjoiZWFydGgifSx7ImlkIjozLCJlZmZlY3QiOiIzIn0seyJpZCI6NCwiZWZmZWN0IjoiNCJ9LHsiaWQiOjUsImVmZmVjdCI6IjUifV0sInBsYXlzTm9kZXMiOlt7ImlkIjowLCJlZmZlY3QiOiIxIn0seyJpZCI6MSwiZWZmZWN0IjoiZmlyZSJ9LHsiaWQiOjIsImVmZmVjdCI6ImVhcnRoIn0seyJpZCI6MywiZWZmZWN0IjoiMiJ9LHsiaWQiOjQsImVmZmVjdCI6ImFpciJ9LHsiaWQiOjUsImVmZmVjdCI6IjMifSx7ImlkIjo2LCJlZmZlY3QiOiJmaXJlIn0seyJpZCI6NywiZWZmZWN0IjoiNCJ9XX0sImlubmF0ZVBvd2VycyI6eyJpc1Zpc2libGUiOmZhbHNlLCJwb3dlcnMiOlt7ImlkIjowLCJuYW1lIjoiRVhQTE9TSVZFIEVSVVBUSU9OIiwic3BlZWQiOiJmYXN0IiwicmFuZ2UiOiIwIiwidGFyZ2V0IjoiYW55IiwidGFyZ2V0VGl0bGUiOiJUQVJHRVQgTEFORCIsIm5vdGUiOiJEZXN0cm95IFggKDEgb3IgbW9yZSkgb2YgeW91ciB7cHJlc2VuY2V9IGluIHRhcmdldCBsYW5kOyB7ZGVzdHJveWVkLXByZXNlbmNlfSBjaGVja3MgaG93IG1hbnkgeW91IGRlc3Ryb3llZC4gVGhpcyBQb3dlciBkb2VzIERhbWFnZSAoc2VwYXJhdGVseSBhbmQgZXF1YWxseSkgdG8gYm90aCBJbnZhZGVycyBhbmQge2RhaGFufS4gUmFuZ2VzIGJlbG93IGNhbid0IGJlIGluY3JlYXNlZC4iLCJub3RlU2hvdyI6dHJ1ZSwibGV2ZWxzIjpbeyJpZCI6MCwidGhyZXNob2xkIjoiMi1maXJlLDItZWFydGgsMi1kZXN0cm95ZWQtcHJlc2VuY2UiLCJlZmZlY3QiOiJJbiBvbmUgbGFuZCB3aXRoaW4ge3JhbmdlLTF9LCBYIERhbWFnZS4iLCJpc0xvbmciOmZhbHNlfSx7ImlkIjoxLCJ0aHJlc2hvbGQiOiIzLWZpcmUsMy1lYXJ0aCw0LWRlc3Ryb3llZC1wcmVzZW5jZSIsImVmZmVjdCI6Ilgge2ZlYXJ9LiIsImlzTG9uZyI6ZmFsc2V9LHsiaWQiOjIsInRocmVzaG9sZCI6IjQtZmlyZSwyLWFpciw0LWVhcnRoLDYtZGVzdHJveWVkLXByZXNlbmNlIiwiZWZmZWN0IjoiSW4gZWFjaCBsYW5kIHdpdGhpbiB7cmFuZ2UtMX0sIDQgRGFtYWdlLiBBZGQgMSB7YmxpZ2h0fSB0byB0YXJnZXQgbGFuZDsgZG9pbmcgc28gZG9lcyBub3QgRGVzdHJveSB5b3VyIHtwcmVzZW5jZX0uIiwiaXNMb25nIjpmYWxzZX0seyJpZCI6MywidGhyZXNob2xkIjoiNS1maXJlLDMtYWlyLDUtZWFydGgsMTAtZGVzdHJveWVkLXByZXNlbmNlIiwiZWZmZWN0IjoiSW4gZWFjaCBsYW5kIHdpdGhpbiB7cmFuZ2UtMn0sICs0IERhbWFnZS4gSW4gZWFjaCBsYW5kIGFkamFjZW50IHRvIHRoZSB0YXJnZXQsIGFkZCAxIHtibGlnaHR9IGlmIGl0IGRvZXNuJ3QgaGF2ZSBhbnkuIiwiaXNMb25nIjp0cnVlfV19LHsiaWQiOjEsIm5hbWUiOiJQT1dFUkVEIEJZIFRIRSBGVVJOQUNFIE9GIFRIRSBFQVJUSCIsInNwZWVkIjoic2xvdyIsInJhbmdlIjoiMCIsInRhcmdldCI6ImFueSIsInRhcmdldFRpdGxlIjoiVEFSR0VUIExBTkQiLCJub3RlIjpudWxsLCJub3RlU2hvdyI6dHJ1ZSwibGV2ZWxzIjpbeyJpZCI6MCwidGhyZXNob2xkIjoiMy1lYXJ0aCIsImVmZmVjdCI6IkFkZCAxIG9mIHlvdXIgZGVzdHJveWVkIHtwcmVzZW5jZX0uIiwiaXNMb25nIjpmYWxzZX0seyJpZCI6MSwidGhyZXNob2xkIjoiMy1maXJlLGNvc3QtMiIsImVmZmVjdCI6IkdhaW4gYSBQb3dlciBDYXJkLiIsImlzTG9uZyI6ZmFsc2V9LHsiaWQiOjIsInRocmVzaG9sZCI6IjQtZWFydGgsNC1maXJlIiwiZWZmZWN0IjoiTW92ZSB1cCB0byAyIG9mIHlvdXIge3ByZXNlbmNlfSBmcm9tIG90aGVyIGxhbmRzIHRvIHRhcmdldCBsYW5kLiIsImlzTG9uZyI6ZmFsc2V9LHsiaWQiOjMsInRocmVzaG9sZCI6IjUtZmlyZSIsImVmZmVjdCI6IlJldHVybiB1cCB0byAyIG9mIHlvdXIgZGVzdHJveWVkIHtwcmVzZW5jZX0gdG8geW91ciB7cHJlc2VuY2V9IHRyYWNrcy4iLCJpc0xvbmciOmZhbHNlfV19XX0sImN1c3RvbUljb25zIjp7ImlzVmlzaWJsZSI6ZmFsc2UsImljb25zIjpbeyJpZCI6MCwibmFtZSI6IiJ9XX19`

**Comment by tomprince** [comment]
If you are doing something like this, I'd be inclined to suggest using JSON (which I think is essentially the internal format used by the app anyway), rather than base64.

**Comment by resonant-gamedesign** [comment]
Right, we could just dump the JSON spirit board file and that would do the
trick.
