### ISSUE TITLE
[Feature Request] support for additional presence tracks

### ISSUE THREAD

**Issue by PointMeAtTheDawn** [spirit-island-builder/spirit-island-builder#388]
It would be nice to have the flexibility to do a Starlight-esque set of tracks. In particular I'm looking to make a 4x4 grid, which the {middle} option doesn't quite support.

**Comment by resonant-gamedesign** [comment]
We've seen this request a lot. I don't think it is going to happen, at least not anytime soon. Implementation would likely take a gut & replace. 

Sorry!

**Comment by resonant-gamedesign** [comment]
@PointMeAtTheDawn I did however add a feature to allow a few more innate powers.
You can test it on Dev:
https://dev.spirit-island-builder.pages.dev/
![image](https://github.com/neubee/spirit-island-builder/assets/44596045/b4dcab41-288c-412e-81af-af5fcbb7c69d)

**Comment by PointMeAtTheDawn** [comment]
Thanks for the response! I'm not sure how I'd use this to make a 4x4 grid, but thanks <3

**Comment by resonant-gamedesign** [comment]
![Volcano_Looming_High_SpiritBoard (13)](https://github.com/neubee/spirit-island-builder/assets/44596045/40717673-26cb-45d4-b2f5-8da84dcd64d1)
What about this? @PointMeAtTheDawn

**Comment by resonant-gamedesign** [comment]
Or...
![Volcano_Looming_High_SpiritBoard (13)](https://github.com/neubee/spirit-island-builder/assets/44596045/3959c8e5-7213-4e74-8971-46ab4370b03b)

**Comment by ediebold** [comment]
That looks amazing! Perfect for what I'm after at least!

Thank you!
