### ISSUE TITLE
The update changed front-end behavior via browser

### ISSUE THREAD

**Issue by kyllebylle** [spirit-island-builder/spirit-island-builder#482]
Since the update a couple of hours ago the Aspect cards I had saved are now a bit scuffed. The font pushes "growth options" to the side. Can replicate the bug with both explorer and firefox.

**Comment by kyllebylle** [comment]
I'm pretty sure I discovered the source of the bug. Since the update: If you do not have a "Replacement" field then the format is a bit scuffed. The Dive seems to float a bit incorrectly then.

**Comment by resonant-gamedesign** [comment]
I'm not getting this bug. Can you send your save file? @kyllebylle

**Comment by resonant-gamedesign** [comment]
For example, this looks OK to me:
<img width="329" alt="image" src="https://github.com/spirit-island-builder/spirit-island-builder/assets/44596045/ef9b8d63-c882-43c7-804e-b7d54f6b96e6">

**Comment by resonant-gamedesign** [comment]
@kyllebylle I'm going to close this issue, I think. Please reopen with more details.
